### ISSUE TITLE
Fix for functions.php

### ISSUE THREAD

**Issue by ghost** [Truman-State-University/truman-digital-sign-theme#1]
Great work with this digital signage theme. I'm looking at using it at my institution. When I created a child theme, I noticed an issue with the functions.php file that prevented 3 files from loading.

The fix: in lines 62-85 of functions.php, change the 3 instances of get_stylesheet_directory_uri() to get_template_directory_uri().

**Comment by mogmarsh** [comment]
fixed with 1.0.12
