### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by baelinc** [Truman-State-University/truman-digital-sign-theme#2]
Is there a way for videos to complete before it moves on to the next slide?

I did a test with a video and it only waits the number of seconds set on the slide.

**Comment by mogmarsh** [comment]
Can you not set the duration on the slide to match the length of the video? Each slide has its own duration setting. It can probably be made smarter at some point.

**Comment by baelinc** [comment]
This particular video is 30 seconds long. The max in the drop down in 20.

**Comment by mogmarsh** [comment]
Ah, valid point. I'll see what I can do for you.

**Comment by baelinc** [comment]
Thanks. It would be a nice feature to have, if it is possible when the system looks at the duration of the video and puts that as the duration. But you still have the ability to shorten it manually.

Thanks for sharing your setup.

**Comment by mogmarsh** [comment]
Version 1.0.13 fixes this by replacing the dropdown with a number field, so you can type any number of seconds that you want.
